[manifest]
version = "1.0.0"
priority = 28

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
#target = 'functions/common_events.lua'
pattern = '''{ key = "Rare" },'''
position = "after"
payload = '''{ key = "Legendary" },'''
match_indent = true
